ALTER TABLE "manpower_requests"
ADD COLUMN "description" TEXT NOT NULL DEFAULT '',
ADD COLUMN "location" TEXT NOT NULL DEFAULT '',
ADD COLUMN "employmentType" TEXT NOT NULL DEFAULT 'FULL_TIME',
ADD COLUMN "minExperience" DOUBLE PRECISION,
ADD COLUMN "maxExperience" DOUBLE PRECISION,
ADD COLUMN "skills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "manpower_requests"
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "location" DROP DEFAULT;
