-- Replace the previous blanket completion flag with the evidence-backed ledger.
UPDATE "feature_catalogue"
SET "status" = 'Not Started', "cursorDone" = false;

UPDATE "feature_catalogue"
SET "status" = 'Done', "cursorDone" = true
WHERE "capability" = 'Configuration';

UPDATE "feature_catalogue"
SET "status" = 'Done', "cursorDone" = true
WHERE "capability" IN ('Create', 'View/Search', 'Update/History', 'API')
  AND "module" = ANY(string_to_array('API Catalogue|Address Verification|Advance|Allocation Dates|Allocation Percentage|Allocation Release|Application Tracking|Appraisal|Approval Engine|Arrear|Asset Assignment|Asset Inventory|Attendance Punch|Audit Log|BGC Case|BGV Package|BGV Vendor Portal|BI Export|Bank Details|Banking|Bench Management|Benefit Enrollment|Benefit Plan|Biometric|Bonus|Branch Setup|Buddy Assignment|Bulk Export|Bulk Import|Business Rule|Business Unit|Calibration|Candidate Conversion|Career Site|Check-in|Client Master|Client URL|Competency Library|Conflict Declaration|Contract|Cost Center|Country Document Checklist|Country Setup|Criminal Check|DSR|Data Catalogue|Data Purging|Delegation|Department|Designation|Disciplinary Action|Document Repository|Document Verification|E-Sign|Education Proof|Education Verification|Email Template|Emergency Contact|Employee Creation|Employment Type|Employment Verification|Engagement Survey|Escalation|Executive Dashboard|Exit Clearance|Expense Claim|Experience Proof|Feature Flags|Feedback|Full & Final|Geofencing|Goal Library|Goal Setting|Grade|Hiring Team|Holiday Calendar|IT Access|Identity Documents|Incentive|Incident Reporting|Induction|Integration Registry|Interview Scheduling|Investigation|JD Library|Job Board|Job Detail|Job Family|Job Listing|Job Requisition|Joining Checklist|KPI Library|Leave Balance|Leave Request|Leave Type|Legal Entity|Legal Hold|Loan|Localization|Location|Manager Review|Manpower Request|Manpower Requisition|Matching Engine|Mobile ESS|Notification Template|Offer Letter|Offer Management|Onboarding Portal|OpenAPI|Organization Profile|Over-allocation|Overtime|POSH Complaint|Payroll Calendar|Payroll Export|Payroll Run|Payslip|Performance Cycle|Personal Data|Policy Library|Position|Position Control|Preboarding Portal|Privacy Consent|Project Allocation|Project Master|Project Skill|Pulse Survey|Rate Card|Rating Scale|Recognition|Recovery|Recruiter Assignment|Reference Check|Regularization|Reimbursement|Report Catalogue|Resignation|Resource Allocation|Resource Match|Resume Parsing|Resume Upload|Retention Policy|Roster|SCIM|SFTP Import|SLA|SMS Template|Salary Component|Salary Structure|Scheduled Job|Self Review|Shift|Shortlisting|Subscription Plan|Support Access|Survey Analytics|Survey Builder|Talent Pool|Tax Declaration|Tax Details|Teams Meeting|Tenant Export|Tenant Provisioning|Tenant Settings|Tenant Suspension|Timesheet|Training Assignment|Training Course|Vacancy Control|Vendor Portal|WhatsApp Template|Whistleblower|Workflow Designer|Zoom Meeting|eNPS', '|'));

UPDATE "feature_catalogue"
SET "status" = 'Done', "cursorDone" = true
WHERE "capability" = 'Workflow/Approval'
  AND "module" = ANY(string_to_array('Application Tracking|Appraisal|Approval Engine|Asset Assignment|Conflict Declaration|Disciplinary Action|Document Verification|Engagement Survey|Exit Clearance|Expense Claim|Full & Final|Goal Setting|Incident Reporting|Interview Scheduling|Investigation|Leave Request|Legal Hold|Manpower Request|Manpower Requisition|Offer Management|Onboarding Portal|POSH Complaint|Pulse Survey|Resignation|Survey Builder|Tax Declaration|Timesheet|Training Assignment|Whistleblower|Workflow Designer|eNPS', '|'));
