export type LifecycleField = {
  key: string;
  label: string;
  type: 'TEXT' | 'TEXTAREA' | 'DATE' | 'NUMBER' | 'EMAIL' | 'PHONE' | 'SELECT' | 'BOOLEAN';
  required?: boolean;
  options?: string[];
};

export type LifecycleTaskTemplate = {
  code: string;
  title: string;
  description?: string;
  required?: boolean;
  ownerRole?: string;
  fields?: LifecycleField[];
};

export type LifecycleDocumentTemplate = {
  code: string;
  title: string;
  category: string;
  description?: string;
  required?: boolean;
  assignedTo?: string;
};

export type LifecycleStageTemplate = {
  key: string;
  title: string;
  description: string;
  ownerRole: string;
  tasks: LifecycleTaskTemplate[];
  documents?: LifecycleDocumentTemplate[];
};

const field = (key: string, label: string, type: LifecycleField['type'] = 'TEXT', required = true, options?: string[]): LifecycleField => ({ key, label, type, required, options });
const task = (code: string, title: string, ownerRole: string, fields: LifecycleField[] = [], description?: string): LifecycleTaskTemplate => ({ code, title, ownerRole, fields, description, required: true });
const doc = (code: string, title: string, category: string, assignedTo = 'Candidate', required = true, description?: string): LifecycleDocumentTemplate => ({ code, title, category, assignedTo, required, description });

export const LIFECYCLE_TEMPLATES: Record<string, { name: string; entityTypes: string[]; stages: LifecycleStageTemplate[] }> = {
  CANDIDATE_INTAKE: {
    name: 'Candidate intake and readiness', entityTypes: ['CANDIDATE'], stages: [
      { key: 'identity', title: 'Identity & contact', description: 'Capture verified contact, identity, location, privacy and communication preferences.', ownerRole: 'RECRUITER', tasks: [
        task('personal_details', 'Personal and contact details', 'RECRUITER', [field('legalFirstName', 'Legal first name'), field('legalMiddleName', 'Legal middle name', 'TEXT', false), field('legalLastName', 'Legal last name'), field('preferredName', 'Preferred name', 'TEXT', false), field('email', 'Primary email', 'EMAIL'), field('phone', 'Mobile number', 'PHONE'), field('alternatePhone', 'Alternate phone', 'PHONE', false), field('dateOfBirth', 'Date of birth', 'DATE', false), field('currentCity', 'Current city'), field('currentCountry', 'Current country')]),
        task('communication', 'Communication and consent', 'RECRUITER', [field('preferredChannel', 'Preferred channel', 'SELECT', true, ['Email', 'Phone', 'SMS', 'WhatsApp']), field('preferredTime', 'Best contact time', 'TEXT', false), field('privacyNotice', 'Privacy notice acknowledged', 'BOOLEAN'), field('marketingConsent', 'Talent-community consent', 'BOOLEAN', false), field('source', 'Candidate source', 'SELECT', true, ['Careers site', 'Agency', 'Referral', 'Job board', 'Social sourcing', 'Walk-in', 'Other'])]),
      ], documents: [doc('identity_proof', 'Government-issued identity evidence', 'Identity'), doc('address_proof', 'Current address evidence', 'Identity', 'Candidate', false)] },
      { key: 'professional', title: 'Professional profile', description: 'Build the searchable employment, education, skill and compensation profile.', ownerRole: 'RECRUITER', tasks: [
        task('career_summary', 'Career summary', 'RECRUITER', [field('headline', 'Professional headline'), field('totalExperienceYears', 'Total experience (years)', 'NUMBER'), field('currentTitle', 'Current title'), field('currentEmployer', 'Current employer', 'TEXT', false), field('industry', 'Industry'), field('summary', 'Professional summary', 'TEXTAREA')]),
        task('skills', 'Skills and proficiency', 'RECRUITER', [field('primarySkills', 'Primary skills', 'TEXTAREA'), field('secondarySkills', 'Secondary skills', 'TEXTAREA', false), field('certifications', 'Certifications', 'TEXTAREA', false), field('languages', 'Languages and proficiency', 'TEXTAREA', false)]),
        task('employment_preferences', 'Employment preferences', 'RECRUITER', [field('employmentType', 'Employment type', 'SELECT', true, ['Permanent', 'Contract', 'Contract-to-hire', 'Temporary', 'Part-time', 'Internship']), field('workMode', 'Work mode', 'SELECT', true, ['On-site', 'Hybrid', 'Remote', 'Flexible']), field('preferredLocations', 'Preferred locations', 'TEXTAREA'), field('noticePeriodDays', 'Notice period (days)', 'NUMBER'), field('availableFrom', 'Available from', 'DATE', false), field('currentCompensation', 'Current compensation', 'NUMBER', false), field('expectedCompensation', 'Expected compensation', 'NUMBER', false), field('currency', 'Compensation currency', 'TEXT', false)]),
      ], documents: [doc('resume', 'Current resume/CV', 'Professional'), doc('education', 'Education certificates', 'Education', 'Candidate', false), doc('certifications', 'Professional certifications', 'Professional', 'Candidate', false)] },
      { key: 'eligibility', title: 'Eligibility & mobility', description: 'Establish work location eligibility, mobility, conflicts, accommodations and availability.', ownerRole: 'HR', tasks: [
        task('work_eligibility', 'Work eligibility declaration', 'HR', [field('targetCountries', 'Countries available to work in', 'TEXTAREA'), field('authorizationSummary', 'Current work authorization', 'TEXTAREA'), field('sponsorshipRequired', 'Sponsorship required', 'BOOLEAN'), field('relocation', 'Open to relocation', 'BOOLEAN'), field('travelPercentage', 'Travel availability (%)', 'NUMBER', false)]),
        task('declarations', 'Hiring declarations', 'HR', [field('conflictOfInterest', 'Potential conflict of interest', 'BOOLEAN'), field('conflictDetails', 'Conflict details', 'TEXTAREA', false), field('accommodationRequired', 'Interview/workplace accommodation required', 'BOOLEAN'), field('accommodationNotes', 'Accommodation notes', 'TEXTAREA', false), field('nonCompete', 'Current non-compete/restriction', 'BOOLEAN', false)]),
      ], documents: [doc('work_authorization', 'Work authorization evidence', 'Compliance', 'Candidate', false)] },
      { key: 'quality', title: 'Quality review', description: 'Resolve duplicates, validate evidence and prepare a complete, searchable candidate record.', ownerRole: 'RECRUITER', tasks: [
        task('duplicate_review', 'Duplicate and source-quality review', 'RECRUITER', [field('duplicateChecked', 'Duplicate search completed', 'BOOLEAN'), field('sourceVerified', 'Source verified', 'BOOLEAN'), field('ownership', 'Candidate ownership/recruiter'), field('qualityNotes', 'Quality review notes', 'TEXTAREA', false)]),
        task('readiness', 'Candidate readiness decision', 'HR', [field('profileComplete', 'Required profile data complete', 'BOOLEAN'), field('documentsComplete', 'Required documents available', 'BOOLEAN'), field('consentValid', 'Processing consent/basis valid', 'BOOLEAN'), field('readiness', 'Readiness decision', 'SELECT', true, ['Ready for matching', 'Needs candidate action', 'Needs recruiter action', 'Hold', 'Do not progress'])]),
      ] },
    ],
  },
  HIRING: {
    name: 'Application to hire', entityTypes: ['APPLICATION'], stages: [
      { key: 'application', title: 'Application', description: 'Confirm requisition fit, application profile, source, consent and required evidence.', ownerRole: 'RECRUITER', tasks: [
        task('application_review', 'Application completeness', 'RECRUITER', [field('source', 'Application source'), field('appliedRole', 'Applied role'), field('appliedLocation', 'Applied location'), field('screeningOwner', 'Screening owner'), field('candidateNoticeDays', 'Notice period (days)', 'NUMBER'), field('salaryExpectation', 'Salary expectation', 'NUMBER', false), field('currency', 'Currency', 'TEXT', false)]),
        task('minimum_criteria', 'Minimum criteria assessment', 'RECRUITER', [field('experienceMatch', 'Experience requirement met', 'BOOLEAN'), field('skillMatch', 'Core skills met', 'BOOLEAN'), field('locationMatch', 'Location/work-mode compatible', 'BOOLEAN'), field('eligibilityMatch', 'Work eligibility compatible', 'BOOLEAN'), field('screeningNotes', 'Assessment notes', 'TEXTAREA')]),
      ], documents: [doc('resume', 'Resume/CV', 'Application'), doc('cover_letter', 'Cover letter', 'Application', 'Candidate', false), doc('portfolio', 'Portfolio/work samples', 'Application', 'Candidate', false)] },
      { key: 'screening', title: 'Screening', description: 'Complete recruiter and hiring-manager screening with documented decisions.', ownerRole: 'RECRUITER', tasks: [
        task('recruiter_screen', 'Recruiter screening', 'RECRUITER', [field('screeningDate', 'Screening date', 'DATE'), field('motivation', 'Motivation for change', 'TEXTAREA'), field('roleUnderstanding', 'Role understanding', 'TEXTAREA'), field('communicationRating', 'Communication rating (1-5)', 'NUMBER'), field('compensationAlignment', 'Compensation aligned', 'BOOLEAN'), field('recommendation', 'Recommendation', 'SELECT', true, ['Proceed', 'Hold', 'Reject'])]),
        task('manager_review', 'Hiring manager review', 'MANAGER', [field('reviewer', 'Hiring manager'), field('technicalFit', 'Technical/functional fit (1-5)', 'NUMBER'), field('teamFit', 'Team fit (1-5)', 'NUMBER'), field('managerComments', 'Manager comments', 'TEXTAREA'), field('decision', 'Decision', 'SELECT', true, ['Interview', 'Additional screen', 'Hold', 'Reject'])]),
      ] },
      { key: 'interviews', title: 'Interviews', description: 'Plan panels, collect structured scorecards and close feedback before decisions.', ownerRole: 'INTERVIEWER', tasks: [
        task('interview_plan', 'Interview plan and panel', 'RECRUITER', [field('rounds', 'Planned rounds', 'TEXTAREA'), field('panel', 'Panel members', 'TEXTAREA'), field('candidateAvailability', 'Candidate availability', 'TEXTAREA'), field('timezone', 'Interview timezone'), field('accessibility', 'Accessibility arrangements', 'TEXTAREA', false)]),
        task('scorecard_closure', 'Scorecard and feedback closure', 'INTERVIEWER', [field('scorecardsExpected', 'Scorecards expected', 'NUMBER'), field('scorecardsReceived', 'Scorecards received', 'NUMBER'), field('overallScore', 'Overall score (1-5)', 'NUMBER'), field('strengths', 'Strengths', 'TEXTAREA'), field('risks', 'Risks/concerns', 'TEXTAREA'), field('panelDecision', 'Panel decision', 'SELECT', true, ['Select', 'Additional round', 'Hold', 'Reject'])]),
      ], documents: [doc('assessment', 'Assessment/work sample', 'Interview', 'Candidate', false), doc('scorecards', 'Completed interview scorecards', 'Interview', 'Interview panel')] },
      { key: 'offer', title: 'Offer', description: 'Complete approvals, compensation, contract terms, candidate negotiation and acceptance.', ownerRole: 'HR', tasks: [
        task('offer_details', 'Offer and employment terms', 'HR', [field('designation', 'Designation'), field('department', 'Department'), field('manager', 'Reporting manager'), field('location', 'Work location'), field('employmentType', 'Employment type'), field('joiningDate', 'Proposed joining date', 'DATE'), field('probationMonths', 'Probation (months)', 'NUMBER', false), field('annualCompensation', 'Annual compensation', 'NUMBER'), field('currency', 'Currency'), field('bonus', 'Variable/bonus', 'NUMBER', false)]),
        task('approval_negotiation', 'Approval and negotiation', 'HR', [field('budgetApproved', 'Budget approval complete', 'BOOLEAN'), field('approver', 'Final approver'), field('offerSentDate', 'Offer sent date', 'DATE'), field('candidateResponse', 'Candidate response', 'SELECT', true, ['Pending', 'Accepted', 'Declined', 'Negotiating']), field('negotiationNotes', 'Negotiation notes', 'TEXTAREA', false)]),
      ], documents: [doc('offer_letter', 'Approved offer letter', 'Offer', 'HR'), doc('compensation_approval', 'Compensation approval', 'Offer', 'Approver'), doc('accepted_offer', 'Candidate-accepted offer', 'Offer', 'Candidate')] },
      { key: 'preboarding', title: 'Preboarding', description: 'Convert the accepted candidate into a joiner with checks, documents and readiness confirmed.', ownerRole: 'HR', tasks: [
        task('joining_readiness', 'Joining readiness', 'HR', [field('joiningConfirmed', 'Joining date confirmed', 'BOOLEAN'), field('noticeReleased', 'Previous-employer release confirmed', 'BOOLEAN', false), field('bgcInitiated', 'Background check initiated', 'BOOLEAN'), field('mobilityClear', 'Work authorization/mobility clear', 'BOOLEAN'), field('preboardingOwner', 'Preboarding owner'), field('riskNotes', 'Joining risks', 'TEXTAREA', false)]),
      ], documents: [doc('identity', 'Identity evidence', 'Preboarding'), doc('address', 'Address evidence', 'Preboarding'), doc('education', 'Education evidence', 'Preboarding'), doc('employment', 'Employment evidence', 'Preboarding', 'Candidate', false), doc('work_authorization', 'Work authorization evidence', 'Preboarding', 'Candidate', false)] },
      { key: 'hired', title: 'Hired / joined', description: 'Confirm conversion, employee record, joining outcome and source closure.', ownerRole: 'HR', tasks: [
        task('conversion', 'Hire conversion', 'HR', [field('employeeCode', 'Employee code'), field('actualJoinDate', 'Actual join date', 'DATE'), field('joined', 'Candidate joined', 'BOOLEAN'), field('noShowReason', 'No-show/decline reason', 'TEXTAREA', false), field('sourceClosure', 'Source/vendor closure complete', 'BOOLEAN'), field('handoffComplete', 'Onboarding handoff complete', 'BOOLEAN')]),
      ] },
    ],
  },
  AGENCY_PLACEMENT: {
    name: 'Agency submission to placement', entityTypes: ['AGENCY_SUBMISSION'], stages: [
      { key: 'client_intake', title: 'Client intake', description: 'Validate client, vacancy, commercial terms and submission rules.', ownerRole: 'AGENCY', tasks: [task('client_requirement', 'Client requirement', 'AGENCY', [field('client', 'Client/legal entity'), field('contact', 'Hiring contact'), field('jobTitle', 'Job title'), field('vacancies', 'Vacancies', 'NUMBER'), field('location', 'Location'), field('employmentType', 'Employment type'), field('budgetRange', 'Budget/rate range'), field('submissionDeadline', 'Submission deadline', 'DATE'), field('mustHave', 'Must-have criteria', 'TEXTAREA'), field('commercialTerms', 'Commercial terms', 'TEXTAREA')])], documents: [doc('client_agreement', 'Client/agency agreement', 'Commercial', 'Agency'), doc('job_description', 'Approved job description', 'Requirement', 'Client')] },
      { key: 'candidate_clearance', title: 'Candidate clearance', description: 'Confirm consent, representation rights, availability and destination compliance.', ownerRole: 'AGENCY', tasks: [task('representation', 'Representation and availability', 'AGENCY', [field('candidateConsent', 'Consent to represent', 'BOOLEAN'), field('exclusiveRepresentation', 'Exclusive representation', 'BOOLEAN', false), field('availability', 'Availability/notice'), field('expectedRate', 'Expected pay/rate', 'NUMBER', false), field('rightToWork', 'Right-to-work assessed', 'BOOLEAN'), field('duplicateSubmission', 'Duplicate submission checked', 'BOOLEAN')])], documents: [doc('right_to_represent', 'Right-to-represent consent', 'Consent'), doc('formatted_resume', 'Client-formatted resume', 'Submission')] },
      { key: 'submission', title: 'Submission', description: 'Send a complete, compliant candidate pack and capture client acknowledgement.', ownerRole: 'AGENCY', tasks: [task('submission_pack', 'Submission pack', 'AGENCY', [field('submittedBy', 'Submitted by'), field('submittedAt', 'Submitted date', 'DATE'), field('sellRate', 'Client bill/sell rate', 'NUMBER', false), field('currency', 'Currency', 'TEXT', false), field('candidateSummary', 'Candidate summary', 'TEXTAREA'), field('complianceSummary', 'Compliance summary', 'TEXTAREA'), field('clientAcknowledged', 'Client acknowledged', 'BOOLEAN')])], documents: [doc('submission_pack', 'Client submission pack', 'Submission', 'Agency'), doc('compliance_snapshot', 'Country compliance snapshot', 'Compliance', 'Agency')] },
      { key: 'client_process', title: 'Client process', description: 'Track shortlisting, interviews, feedback and selection.', ownerRole: 'AGENCY', tasks: [task('client_feedback', 'Client process and feedback', 'AGENCY', [field('clientStatus', 'Client status', 'SELECT', true, ['Submitted', 'Shortlisted', 'Interviewing', 'Selected', 'Rejected', 'On hold']), field('interviewSchedule', 'Interview schedule', 'TEXTAREA', false), field('feedback', 'Client feedback', 'TEXTAREA', false), field('nextAction', 'Next action'), field('nextActionDate', 'Next-action date', 'DATE')])] },
      { key: 'placement', title: 'Placement', description: 'Finalize offer/contract, start, billing trigger and guarantee period.', ownerRole: 'AGENCY', tasks: [task('placement_terms', 'Placement and billing terms', 'AGENCY', [field('placementType', 'Placement type', 'SELECT', true, ['Permanent', 'Contract', 'Contract-to-hire', 'Temporary']), field('startDate', 'Start date', 'DATE'), field('agreedPay', 'Candidate pay', 'NUMBER'), field('billRate', 'Client bill/fee', 'NUMBER'), field('currency', 'Currency'), field('feeType', 'Fee type', 'SELECT', true, ['Percentage', 'Fixed fee', 'Hourly markup', 'Daily markup']), field('invoiceTrigger', 'Invoice trigger'), field('guaranteeEnd', 'Guarantee/replacement period end', 'DATE', false), field('placementConfirmed', 'Placement confirmed', 'BOOLEAN')])], documents: [doc('client_contract', 'Client placement/assignment contract', 'Contract', 'Client'), doc('candidate_contract', 'Candidate employment/assignment contract', 'Contract', 'Candidate'), doc('purchase_order', 'Purchase order/work order', 'Commercial', 'Client', false)] },
    ],
  },
  GLOBAL_MOBILITY: {
    name: 'Work authorization and global mobility', entityTypes: ['WORK_AUTHORIZATION'], stages: [
      { key: 'assessment', title: 'Eligibility', description: 'Assess destination, route, employer, role, worksite and sponsorship eligibility.', ownerRole: 'MOBILITY', tasks: [task('eligibility_assessment', 'Immigration and work-right assessment', 'MOBILITY', [field('destinationCountry', 'Destination country'), field('memberState', 'EU member state', 'TEXT', false), field('authorizationType', 'Authorization/visa type'), field('employerLegalName', 'Sponsoring employer/legal entity'), field('jobTitle', 'Job title'), field('occupationCode', 'Occupation/SOC/NOC code', 'TEXT', false), field('workLocation', 'Worksite/location'), field('salary', 'Salary/guaranteed pay', 'NUMBER', false), field('currency', 'Currency', 'TEXT', false), field('sponsorshipRequired', 'Sponsorship required', 'BOOLEAN'), field('assessmentOutcome', 'Assessment outcome', 'SELECT', true, ['Eligible', 'Potentially eligible', 'Alternative route required', 'Not eligible']), field('assessmentNotes', 'Assessment notes', 'TEXTAREA')])], documents: [doc('passport', 'Passport/travel document', 'Identity'), doc('current_status', 'Current immigration/status evidence', 'Immigration', 'Candidate', false)] },
      { key: 'documents', title: 'Documents', description: 'Assign, receive and verify every candidate and employer document required for the selected route.', ownerRole: 'MOBILITY', tasks: [task('document_plan', 'Document plan', 'MOBILITY', [field('candidateOwner', 'Candidate document owner'), field('employerOwner', 'Employer document owner'), field('targetFilingDate', 'Target filing date', 'DATE'), field('translationRequired', 'Certified translation required', 'BOOLEAN'), field('attestationRequired', 'Legalization/attestation required', 'BOOLEAN'), field('documentNotes', 'Document instructions', 'TEXTAREA')])], documents: [doc('passport_biodata', 'Passport biodata page', 'Identity'), doc('photograph', 'Compliant photograph', 'Identity', 'Candidate', false), doc('education_credentials', 'Education/qualification credentials', 'Qualification'), doc('employment_letters', 'Employment/reference letters', 'Experience', 'Candidate', false), doc('employer_registration', 'Employer registration/licence', 'Employer', 'Employer'), doc('employment_contract', 'Signed employment contract/offer', 'Employment'), doc('dependant_documents', 'Dependant civil documents', 'Dependants', 'Candidate', false)] },
      { key: 'sponsorship', title: 'Sponsorship / filing', description: 'Manage employer approvals, government filings, fees, requests and decisions.', ownerRole: 'MOBILITY', tasks: [task('filing', 'Sponsorship and filing details', 'MOBILITY', [field('sponsorReference', 'Sponsor/employer reference', 'TEXT', false), field('petitionApplicationNo', 'Petition/application number', 'TEXT', false), field('filedAt', 'Filed/submitted date', 'DATE'), field('filingChannel', 'Filing channel/authority'), field('governmentFee', 'Government fee', 'NUMBER', false), field('professionalFee', 'Professional fee', 'NUMBER', false), field('processingType', 'Processing type', 'SELECT', false, ['Standard', 'Priority/Premium', 'Expedited']), field('biometricsDate', 'Biometrics appointment', 'DATE', false), field('medicalDate', 'Medical appointment', 'DATE', false), field('decisionDue', 'Expected decision date', 'DATE', false)])], documents: [doc('filing_receipt', 'Filing/acknowledgement receipt', 'Government'), doc('payment_receipt', 'Government fee receipt', 'Government', 'Employer', false), doc('request_for_evidence', 'Authority information request/response', 'Government', 'Case owner', false)] },
      { key: 'verification', title: 'Verification', description: 'Record the official decision, right-to-work verification and conditions.', ownerRole: 'HR', tasks: [task('authorization_verification', 'Authorization verification', 'HR', [field('decision', 'Decision', 'SELECT', true, ['Approved', 'Refused', 'Withdrawn', 'Pending']), field('decisionDate', 'Decision date', 'DATE'), field('validFrom', 'Valid from', 'DATE'), field('expiresAt', 'Expiry date', 'DATE'), field('verificationMethod', 'Verification method'), field('verificationReference', 'Verification reference'), field('workRestrictions', 'Work restrictions/conditions', 'TEXTAREA', false), field('reverificationDate', 'Reverification date', 'DATE', false), field('verifiedBy', 'Verified by')])], documents: [doc('approval_notice', 'Approval/decision notice', 'Government'), doc('permit_visa', 'Issued visa/work permit/residence evidence', 'Immigration'), doc('right_to_work_check', 'Right-to-work verification record', 'Compliance', 'HR')] },
      { key: 'deployment', title: 'Deployment', description: 'Complete travel, arrival, local registration, payroll and start authorization.', ownerRole: 'HR', tasks: [task('deployment_readiness', 'Deployment readiness', 'HR', [field('travelDate', 'Travel/arrival date', 'DATE', false), field('localAddress', 'Destination address', 'TEXTAREA', false), field('nationalId', 'Local ID reference (masked)', 'TEXT', false), field('payrollReady', 'Payroll/tax registration ready', 'BOOLEAN'), field('insuranceReady', 'Insurance/benefits ready', 'BOOLEAN'), field('managerConfirmed', 'Manager/start confirmed', 'BOOLEAN'), field('deploymentDate', 'Authorized deployment date', 'DATE'), field('orientationComplete', 'Local orientation complete', 'BOOLEAN')])], documents: [doc('entry_record', 'Entry/arrival record', 'Travel', 'Candidate', false), doc('local_id', 'Local residence/national ID evidence', 'Immigration', 'Candidate', false), doc('deployment_clearance', 'HR deployment clearance', 'Compliance', 'HR')] },
      { key: 'renewal', title: 'Renewal / closure', description: 'Monitor expiry, extensions, transfers, changes, cancellation and records retention.', ownerRole: 'MOBILITY', tasks: [task('ongoing_compliance', 'Ongoing compliance and renewal', 'MOBILITY', [field('nextReviewDate', 'Next review date', 'DATE'), field('renewalStartDate', 'Renewal initiation date', 'DATE', false), field('changeReported', 'Material changes reported', 'BOOLEAN'), field('changeDetails', 'Role/location/employer changes', 'TEXTAREA', false), field('caseOutcome', 'Case outcome', 'SELECT', true, ['Active', 'Renewed', 'Transferred', 'Permanent status', 'Expired', 'Cancelled', 'Employee departed']), field('closureDate', 'Closure/cancellation date', 'DATE', false), field('retentionUntil', 'Record retention until', 'DATE', false)])], documents: [doc('renewal_filing', 'Renewal/extension filing', 'Renewal', 'Case owner', false), doc('cancellation', 'Cancellation/exit evidence', 'Closure', 'Employer', false)] },
    ],
  },
  ONBOARDING: {
    name: 'Employee onboarding', entityTypes: ['ONBOARDING_CASE'], stages: [
      { key: 'personal', title: 'Personal profile', description: 'Complete employee identity, contact, emergency, address and demographic information.', ownerRole: 'EMPLOYEE', tasks: [task('employee_profile', 'Employee personal profile', 'EMPLOYEE', [field('legalName', 'Legal name'), field('preferredName', 'Preferred name', 'TEXT', false), field('personalEmail', 'Personal email', 'EMAIL'), field('mobile', 'Mobile number', 'PHONE'), field('dateOfBirth', 'Date of birth', 'DATE', false), field('nationality', 'Nationality'), field('maritalStatus', 'Marital status', 'TEXT', false), field('currentAddress', 'Current address', 'TEXTAREA'), field('permanentAddress', 'Permanent address', 'TEXTAREA', false), field('emergencyName', 'Emergency contact name'), field('emergencyRelation', 'Emergency contact relationship'), field('emergencyPhone', 'Emergency contact phone', 'PHONE')])], documents: [doc('identity', 'Government identity evidence', 'Identity'), doc('address', 'Address evidence', 'Identity')] },
      { key: 'employment', title: 'Employment setup', description: 'Confirm position, organization, manager, employment terms and work arrangements.', ownerRole: 'HR', tasks: [task('employment_record', 'Employment record', 'HR', [field('employeeCode', 'Employee code'), field('legalEntity', 'Legal entity'), field('businessUnit', 'Business unit', 'TEXT', false), field('department', 'Department'), field('designation', 'Designation'), field('grade', 'Grade/level', 'TEXT', false), field('employmentType', 'Employment type'), field('manager', 'Reporting manager'), field('location', 'Work location'), field('workMode', 'Work mode'), field('joinDate', 'Joining date', 'DATE'), field('probationEnd', 'Probation end date', 'DATE', false), field('costCenter', 'Cost center', 'TEXT', false)])], documents: [doc('accepted_offer', 'Accepted offer/employment contract', 'Employment'), doc('release_letter', 'Previous-employer release letter', 'Employment', 'Employee', false)] },
      { key: 'verification', title: 'Checks & documents', description: 'Track mandatory documents, background checks, references, work rights and exceptions.', ownerRole: 'HR', tasks: [task('verification_plan', 'Verification and BGC plan', 'HR', [field('package', 'Background-check package'), field('vendor', 'Verification vendor', 'TEXT', false), field('initiatedAt', 'Initiated date', 'DATE'), field('expectedAt', 'Expected completion', 'DATE'), field('identityResult', 'Identity result', 'SELECT', false, ['Pending', 'Clear', 'Review', 'Failed']), field('employmentResult', 'Employment result', 'SELECT', false, ['Pending', 'Clear', 'Review', 'Failed']), field('educationResult', 'Education result', 'SELECT', false, ['Pending', 'Clear', 'Review', 'Failed']), field('criminalResult', 'Criminal result', 'SELECT', false, ['Pending', 'Clear', 'Review', 'Failed']), field('overallResult', 'Overall result', 'SELECT', true, ['Pending', 'Clear', 'Conditional', 'Adverse']), field('exceptionApproval', 'Exception/waiver approval', 'TEXTAREA', false)])], documents: [doc('education', 'Education certificates', 'Verification'), doc('employment', 'Employment proof/references', 'Verification'), doc('background_report', 'Background verification report', 'Verification', 'HR'), doc('work_authorization', 'Work authorization/right-to-work evidence', 'Compliance', 'Employee', false)] },
      { key: 'payroll', title: 'Payroll & benefits', description: 'Capture payment, tax, statutory, benefits and payroll-calendar information.', ownerRole: 'PAYROLL', tasks: [task('payroll_profile', 'Payroll and statutory profile', 'PAYROLL', [field('bankName', 'Bank name'), field('accountHolder', 'Account holder name'), field('accountMasked', 'Account number (masked)'), field('bankCode', 'Routing/IFSC/sort code', 'TEXT', false), field('taxIdentifierMasked', 'Tax identifier (masked)', 'TEXT', false), field('taxRegime', 'Tax regime/category', 'TEXT', false), field('payGroup', 'Pay group'), field('payFrequency', 'Pay frequency'), field('baseSalary', 'Base salary', 'NUMBER'), field('currency', 'Currency'), field('benefitPlan', 'Benefit plan', 'TEXT', false), field('dependants', 'Benefit dependants', 'TEXTAREA', false), field('payrollApproved', 'Payroll profile approved', 'BOOLEAN')])], documents: [doc('bank_proof', 'Bank account evidence', 'Payroll'), doc('tax_form', 'Tax declaration/withholding form', 'Tax'), doc('benefit_nomination', 'Benefits/dependant nomination', 'Benefits', 'Employee', false)] },
      { key: 'workplace', title: 'Access & equipment', description: 'Provision identity, systems, workplace, assets, security and manager readiness.', ownerRole: 'IT', tasks: [task('access_provisioning', 'Access provisioning', 'IT', [field('corporateEmail', 'Corporate email'), field('directoryId', 'Directory/user ID'), field('roleProfile', 'Access role/profile'), field('systems', 'Systems/applications', 'TEXTAREA'), field('mfaEnabled', 'MFA enabled', 'BOOLEAN'), field('securityTraining', 'Security training assigned', 'BOOLEAN')]), task('asset_workplace', 'Assets and workplace', 'IT', [field('assetItems', 'Assigned assets', 'TEXTAREA'), field('assetTag', 'Primary asset tag', 'TEXT', false), field('deskLocation', 'Desk/site details', 'TEXT', false), field('remoteKit', 'Remote-work kit', 'TEXTAREA', false), field('managerReady', 'Manager ready for joiner', 'BOOLEAN')])], documents: [doc('asset_acknowledgement', 'Asset handover acknowledgement', 'Asset', 'Employee'), doc('access_approval', 'System access approval', 'Access', 'Manager')] },
      { key: 'induction', title: 'Induction', description: 'Complete orientation, policies, mandatory training, team introductions and goals.', ownerRole: 'HR', tasks: [task('induction_plan', 'Induction and first-week plan', 'HR', [field('orientationDate', 'Orientation date', 'DATE'), field('buddy', 'Buddy/mentor'), field('teamIntroduction', 'Team introduction complete', 'BOOLEAN'), field('policyAcknowledgements', 'Mandatory policies acknowledged', 'BOOLEAN'), field('mandatoryTraining', 'Mandatory training complete', 'BOOLEAN'), field('firstWeekPlan', 'First-week plan', 'TEXTAREA'), field('initialGoals', 'Initial 30/60/90-day goals', 'TEXTAREA')])], documents: [doc('policy_ack', 'Policy acknowledgements', 'Policy', 'Employee'), doc('training_completion', 'Mandatory training completion', 'Training', 'Employee')] },
      { key: 'activation', title: 'Activation', description: 'Final HR/manager review and controlled activation into the employee population.', ownerRole: 'HR', tasks: [task('activation_review', 'Final activation review', 'HR', [field('mandatoryTasksComplete', 'Mandatory tasks complete', 'BOOLEAN'), field('mandatoryDocsVerified', 'Mandatory documents verified', 'BOOLEAN'), field('bgcCleared', 'Background check clear/approved', 'BOOLEAN'), field('payrollReady', 'Payroll ready', 'BOOLEAN'), field('accessReady', 'Access and assets ready', 'BOOLEAN'), field('managerSignoff', 'Manager sign-off', 'BOOLEAN'), field('hrSignoff', 'HR sign-off', 'BOOLEAN'), field('activationDate', 'Activation date', 'DATE')])], documents: [doc('onboarding_signoff', 'Onboarding completion sign-off', 'Completion', 'HR')] },
    ],
  },
  EMPLOYEE_LIFECYCLE: {
    name: 'Active employee lifecycle', entityTypes: ['EMPLOYEE'], stages: [
      { key: 'employment', title: 'Employment', description: 'Maintain current organization, job, manager, location, status and employment terms.', ownerRole: 'HR', tasks: [task('employment_snapshot', 'Current employment record', 'HR', [field('legalEntity', 'Legal entity'), field('department', 'Department'), field('designation', 'Designation'), field('grade', 'Grade'), field('manager', 'Manager'), field('location', 'Location'), field('workMode', 'Work mode'), field('employmentType', 'Employment type'), field('effectiveFrom', 'Effective from', 'DATE'), field('contractEnd', 'Contract end date', 'DATE', false)])], documents: [doc('current_contract', 'Current employment contract/amendment', 'Employment', 'HR')] },
      { key: 'compensation', title: 'Pay & benefits', description: 'Track salary review, payroll, tax, benefits and employee changes.', ownerRole: 'PAYROLL', tasks: [task('compensation_snapshot', 'Compensation and benefits review', 'PAYROLL', [field('basePay', 'Base pay', 'NUMBER'), field('currency', 'Currency'), field('payFrequency', 'Pay frequency'), field('variableTarget', 'Variable target', 'NUMBER', false), field('lastReviewDate', 'Last pay review', 'DATE', false), field('nextReviewDate', 'Next pay review', 'DATE', false), field('benefitPlan', 'Benefit plan', 'TEXT', false), field('taxProfileValid', 'Tax profile current', 'BOOLEAN'), field('bankProfileValid', 'Bank profile current', 'BOOLEAN')])], documents: [doc('salary_revision', 'Latest salary revision letter', 'Compensation', 'HR', false), doc('benefit_election', 'Current benefits election', 'Benefits', 'Employee', false)] },
      { key: 'performance', title: 'Performance', description: 'Maintain goals, check-ins, review cycle, development and performance actions.', ownerRole: 'MANAGER', tasks: [task('performance_plan', 'Goals and performance plan', 'MANAGER', [field('cycle', 'Performance cycle'), field('goalsDefined', 'Goals defined', 'BOOLEAN'), field('goalSummary', 'Goal summary', 'TEXTAREA'), field('lastCheckIn', 'Last check-in', 'DATE', false), field('nextCheckIn', 'Next check-in', 'DATE'), field('performanceStatus', 'Performance status', 'SELECT', true, ['On track', 'Needs support', 'Exceeding', 'Performance plan']), field('managerNotes', 'Manager notes', 'TEXTAREA', false)])], documents: [doc('performance_review', 'Latest performance review', 'Performance', 'Manager', false)] },
      { key: 'growth', title: 'Learning & career', description: 'Track skills, mandatory learning, development plan, succession and internal mobility.', ownerRole: 'MANAGER', tasks: [task('development_plan', 'Development and career plan', 'MANAGER', [field('strengths', 'Strengths', 'TEXTAREA'), field('skillGaps', 'Skill gaps', 'TEXTAREA'), field('developmentActions', 'Development actions', 'TEXTAREA'), field('mandatoryTrainingDue', 'Mandatory training due', 'DATE', false), field('careerInterest', 'Career interests', 'TEXTAREA', false), field('mobilityInterest', 'Internal mobility interest', 'BOOLEAN'), field('successionReadiness', 'Succession readiness', 'TEXT', false)])], documents: [doc('certification', 'New qualification/certification', 'Learning', 'Employee', false)] },
      { key: 'operations', title: 'Time, leave & assets', description: 'Review attendance, leave, timesheets, assignment, asset and operational compliance.', ownerRole: 'HR', tasks: [task('operational_review', 'Operational compliance review', 'HR', [field('shift', 'Current shift', 'TEXT', false), field('leaveCalendar', 'Leave calendar'), field('timesheetRequired', 'Timesheet required', 'BOOLEAN'), field('timesheetsCurrent', 'Timesheets current', 'BOOLEAN'), field('assetsCurrent', 'Asset register current', 'BOOLEAN'), field('projectAssignment', 'Project/client assignment', 'TEXT', false), field('operationalIssues', 'Open operational issues', 'TEXTAREA', false)])], documents: [doc('asset_register', 'Signed asset register', 'Asset', 'Employee', false)] },
      { key: 'compliance', title: 'Compliance & changes', description: 'Monitor policy, work authorization, personal-data changes and employee relations actions.', ownerRole: 'HR', tasks: [task('compliance_review', 'Employee compliance review', 'HR', [field('policyCurrent', 'Policy acknowledgements current', 'BOOLEAN'), field('workAuthorizationValid', 'Work authorization valid', 'BOOLEAN'), field('workAuthorizationExpiry', 'Work authorization expiry', 'DATE', false), field('personalDataReviewed', 'Personal data reviewed', 'BOOLEAN'), field('conflictDeclaration', 'Conflict declaration current', 'BOOLEAN'), field('caseNotes', 'Open compliance/employee-relations matters', 'TEXTAREA', false), field('nextReview', 'Next compliance review', 'DATE')])], documents: [doc('work_authorization', 'Current work authorization', 'Compliance', 'Employee', false), doc('policy_declaration', 'Annual declarations', 'Compliance', 'Employee', false)] },
    ],
  },
  CONTRACTOR_LIFECYCLE: {
    name: 'Contractor assignment lifecycle', entityTypes: ['CONTRACTOR_ASSIGNMENT'], stages: [
      { key: 'requirement', title: 'Requirement', description: 'Confirm client, role, dates, rate, location and delivery ownership.', ownerRole: 'STAFFING', tasks: [task('assignment_requirement', 'Assignment requirement', 'STAFFING', [field('client', 'Client'), field('role', 'Role/title'), field('location', 'Location'), field('workMode', 'Work mode'), field('startDate', 'Start date', 'DATE'), field('endDate', 'End date', 'DATE', false), field('skills', 'Required skills', 'TEXTAREA'), field('workingHours', 'Working hours'), field('billRate', 'Bill rate', 'NUMBER'), field('currency', 'Currency')])], documents: [doc('work_order', 'Client work order/SOW', 'Commercial', 'Client')] },
      { key: 'compliance', title: 'Compliance', description: 'Complete identity, eligibility, screening, insurance and client compliance.', ownerRole: 'STAFFING', tasks: [task('contractor_compliance', 'Contractor compliance', 'STAFFING', [field('identityVerified', 'Identity verified', 'BOOLEAN'), field('rightToWorkVerified', 'Right-to-work verified', 'BOOLEAN'), field('backgroundClear', 'Background check clear', 'BOOLEAN'), field('insuranceRequired', 'Insurance required', 'BOOLEAN'), field('insuranceExpiry', 'Insurance expiry', 'DATE', false), field('clientTraining', 'Client training complete', 'BOOLEAN')])], documents: [doc('identity', 'Identity evidence', 'Identity'), doc('work_authorization', 'Work authorization', 'Compliance', 'Contractor', false), doc('background_report', 'Background report', 'Compliance'), doc('insurance', 'Insurance certificate', 'Insurance', 'Contractor', false)] },
      { key: 'contract', title: 'Contract', description: 'Finalize worker and client contracts, rates, approvals and purchase order.', ownerRole: 'STAFFING', tasks: [task('contract_terms', 'Contract and rate terms', 'STAFFING', [field('workerType', 'Worker type'), field('payRate', 'Pay rate', 'NUMBER'), field('billRate', 'Bill rate', 'NUMBER'), field('currency', 'Currency'), field('overtimeRule', 'Overtime rule'), field('paymentTerms', 'Payment terms'), field('noticeTerms', 'Notice/termination terms'), field('approvedBy', 'Approved by')])], documents: [doc('worker_contract', 'Worker contract', 'Contract', 'Contractor'), doc('client_contract', 'Client contract/SOW', 'Contract', 'Client'), doc('purchase_order', 'Purchase order', 'Commercial', 'Client', false)] },
      { key: 'deployment', title: 'Deployment', description: 'Provision access, assets, induction, manager acceptance and start confirmation.', ownerRole: 'STAFFING', tasks: [task('deployment', 'Deployment readiness', 'STAFFING', [field('clientManager', 'Client manager'), field('startConfirmed', 'Start confirmed', 'BOOLEAN'), field('accessReady', 'Access ready', 'BOOLEAN'), field('assetIssued', 'Asset issued', 'BOOLEAN'), field('inductionComplete', 'Induction complete', 'BOOLEAN'), field('actualStart', 'Actual start date', 'DATE')])], documents: [doc('access_ack', 'Access/asset acknowledgement', 'Deployment', 'Contractor', false)] },
      { key: 'delivery', title: 'Time & delivery', description: 'Track time approvals, performance, extensions, billing and issues.', ownerRole: 'STAFFING', tasks: [task('delivery_control', 'Assignment delivery control', 'STAFFING', [field('timesheetFrequency', 'Timesheet frequency'), field('approver', 'Timesheet approver'), field('timesheetsCurrent', 'Timesheets current', 'BOOLEAN'), field('invoiceCurrent', 'Billing current', 'BOOLEAN'), field('performanceStatus', 'Performance status'), field('extensionDecisionDate', 'Extension decision due', 'DATE', false), field('deliveryIssues', 'Delivery/issues', 'TEXTAREA', false)])] },
      { key: 'offboarding', title: 'Offboarding', description: 'Close time, access, assets, invoices, documents and redeployment.', ownerRole: 'STAFFING', tasks: [task('contractor_close', 'Assignment closeout', 'STAFFING', [field('lastWorkingDay', 'Last working day', 'DATE'), field('finalTimesheet', 'Final timesheet approved', 'BOOLEAN'), field('accessRevoked', 'Access revoked', 'BOOLEAN'), field('assetsReturned', 'Assets returned', 'BOOLEAN'), field('finalInvoice', 'Final invoice complete', 'BOOLEAN'), field('clientFeedback', 'Client feedback', 'TEXTAREA', false), field('redeploymentStatus', 'Redeployment status', 'SELECT', true, ['Available', 'Redeployed', 'Not available', 'Do not redeploy'])])], documents: [doc('return_receipt', 'Asset/access return evidence', 'Offboarding', 'Contractor', false), doc('assignment_completion', 'Assignment completion/experience letter', 'Offboarding', 'Agency', false)] },
    ],
  },
  EXIT: {
    name: 'Employee exit and settlement', entityTypes: ['RESIGNATION'], stages: [
      { key: 'request', title: 'Exit request', description: 'Capture resignation/termination details, dates, reason, risks and employee communication.', ownerRole: 'HR', tasks: [task('exit_request', 'Exit request details', 'HR', [field('exitType', 'Exit type', 'SELECT', true, ['Resignation', 'Termination', 'Retirement', 'Contract completion', 'Redundancy', 'Absconding', 'Death']), field('reasonCategory', 'Reason category'), field('reasonDetails', 'Reason details', 'TEXTAREA'), field('submittedAt', 'Submitted/initiated date', 'DATE'), field('requestedLastDay', 'Requested last day', 'DATE'), field('noticeDays', 'Notice period (days)', 'NUMBER'), field('riskLevel', 'Business/employee risk', 'SELECT', true, ['Low', 'Medium', 'High', 'Critical']), field('confidential', 'Confidential handling required', 'BOOLEAN')])], documents: [doc('resignation_letter', 'Resignation/exit initiation letter', 'Exit', 'Employee', false), doc('termination_approval', 'Termination/business approval', 'Exit', 'HR', false)] },
      { key: 'approval', title: 'Approval & dates', description: 'Resolve notice, approvals, retention discussion and final working date.', ownerRole: 'MANAGER', tasks: [task('exit_approval', 'Approval and date finalization', 'MANAGER', [field('managerDecision', 'Manager decision', 'SELECT', true, ['Accept', 'Retention discussion', 'Reject/return', 'Escalate']), field('retentionOutcome', 'Retention outcome', 'TEXTAREA', false), field('noticeWaiverDays', 'Notice waived/recovered days', 'NUMBER', false), field('agreedLastDay', 'Agreed last working day', 'DATE'), field('hrApproved', 'HR approved', 'BOOLEAN'), field('businessApproved', 'Business approved', 'BOOLEAN'), field('communicationSent', 'Employee confirmation sent', 'BOOLEAN')])], documents: [doc('acceptance_letter', 'Resignation acceptance/exit confirmation', 'Exit', 'HR')] },
      { key: 'handover', title: 'Handover', description: 'Complete knowledge, work, client, document and successor handover.', ownerRole: 'MANAGER', tasks: [task('knowledge_handover', 'Knowledge and responsibility handover', 'MANAGER', [field('handoverOwner', 'Handover recipient'), field('projects', 'Projects/responsibilities', 'TEXTAREA'), field('documentsLocation', 'Document/repository location', 'TEXTAREA'), field('clientHandover', 'Client/stakeholder handover', 'TEXTAREA', false), field('openItems', 'Open actions/risks', 'TEXTAREA'), field('handoverAccepted', 'Handover accepted', 'BOOLEAN')])], documents: [doc('handover_checklist', 'Signed handover checklist', 'Handover', 'Manager')] },
      { key: 'clearance', title: 'Clearances', description: 'Close departmental, security, access, asset, finance and compliance obligations.', ownerRole: 'HR', tasks: [task('department_clearance', 'Departmental clearance control', 'HR', [field('managerClearance', 'Manager clearance', 'BOOLEAN'), field('itClearance', 'IT/access clearance', 'BOOLEAN'), field('assetClearance', 'Asset clearance', 'BOOLEAN'), field('financeClearance', 'Finance/expense clearance', 'BOOLEAN'), field('adminClearance', 'Admin/facility clearance', 'BOOLEAN'), field('hrClearance', 'HR clearance', 'BOOLEAN'), field('pendingRecovery', 'Pending recoveries/issues', 'TEXTAREA', false)])], documents: [doc('clearance_form', 'Departmental clearance/NOC', 'Clearance', 'HR'), doc('asset_return', 'Asset return receipt', 'Clearance', 'Employee', false)] },
      { key: 'settlement', title: 'Settlement', description: 'Calculate earnings, leave, notice, deductions, recoveries, tax and net settlement.', ownerRole: 'PAYROLL', tasks: [task('final_settlement', 'Full and final settlement', 'PAYROLL', [field('salaryThrough', 'Salary payable through', 'DATE'), field('unpaidSalary', 'Unpaid salary', 'NUMBER'), field('leaveEncashment', 'Leave encashment', 'NUMBER'), field('bonusCommission', 'Bonus/commission', 'NUMBER', false), field('noticeRecovery', 'Notice recovery', 'NUMBER', false), field('assetRecovery', 'Asset/other recovery', 'NUMBER', false), field('taxDeduction', 'Tax deduction', 'NUMBER', false), field('netPayable', 'Net payable', 'NUMBER'), field('currency', 'Currency'), field('paymentDate', 'Payment date', 'DATE'), field('employeeAccepted', 'Employee accepted calculation', 'BOOLEAN')])], documents: [doc('settlement_statement', 'Full and final settlement statement', 'Settlement', 'Payroll'), doc('payment_proof', 'Settlement payment evidence', 'Settlement', 'Payroll')] },
      { key: 'closure', title: 'Closure & alumni', description: 'Issue statutory/employment letters, conduct feedback, revoke access and close records.', ownerRole: 'HR', tasks: [task('exit_closure', 'Exit closure', 'HR', [field('accessRevokedAt', 'Access revoked date', 'DATE'), field('exitInterviewCompleted', 'Exit interview completed', 'BOOLEAN'), field('rehireEligibility', 'Rehire eligibility', 'SELECT', true, ['Eligible', 'Conditional', 'Not eligible']), field('alumniConsent', 'Alumni communication consent', 'BOOLEAN', false), field('recordsClosed', 'Employee record closed', 'BOOLEAN'), field('employeeStatusExited', 'Employee status changed to exited', 'BOOLEAN'), field('closureDate', 'Closure date', 'DATE')])], documents: [doc('experience_letter', 'Experience/service letter', 'Closure', 'HR'), doc('relieving_letter', 'Relieving/release letter', 'Closure', 'HR'), doc('tax_document', 'Final tax/payroll document', 'Closure', 'Payroll', false)] },
    ],
  },
};

export function lifecycleTemplate(code: string) {
  return LIFECYCLE_TEMPLATES[code.trim().toUpperCase()];
}
